### ISSUE TITLE
Conversion from AKA to $

### ISSUE THREAD

**Issue by karlakrrasco** [akroma-project/akroma-wallet-mobile#127]
Use an API that can return the real-time value of AKA to transfer the value of AKA to Dollars, so that this information can be displayed on the Home View balance.

**Comment by detroitpro** [comment]
I am sure there are other APIs, but we should review what it takes to use the Coinbase API: 

https://www.coinbase.com/converter/aka/usd

**Comment by adonayvasquezz** [comment]
@detroitpro I've checked the coinbase API but it looks like it's for advanced features and it's not free. I implemented the Coingecko API, but they ask for a mention like "Data provided by CoinGecko" or "Data by CoinGecko"

**Comment by detroitpro** [comment]
@adonayvasquezz - that is fine, work with @landaverde1196 to put that notice somewhere
