### ISSUE TITLE
Export Key View After Creating a Wallet

### ISSUE THREAD

**Issue by karlakrrasco** [akroma-project/akroma-wallet-mobile#130]
Once a user creates a wallet it should take him to the Export KeyStore screen as a reminder that will need to import the key store to access his wallet again.

**Comment by detroitpro** [comment]
I'm confused about this. 

When a user creates a wallet, the keystore file is created (and stored local). @landaverde1196 @karlakrrasco can you provide more detail on what you are thinking for this workflow?
