### ISSUE TITLE
"Sign In" Functionality

### ISSUE THREAD

**Issue by karlakrrasco** [akroma-project/akroma-wallet-mobile#131]
There is a new screen created in the mobile app that will work similarly to a sign-in, which will have two buttons 

- New Users: Once a user opens the app it will show the button "Create a new Wallet"
- Frequent User: Once a user opens the app it will show the button "Insert Private Key" 

Figma Link: https://www.figma.com/file/eKAMTZh44NN3WBBeVNdXJm/Akroma-Wallet?node-id=375%3A6462&t=qUeyitounMEwg3CR-0

![Image](https://user-images.githubusercontent.com/104467313/213567662-6e27decb-a604-4cdf-bad0-def04326a239.png)

**Comment by detroitpro** [comment]
I'd like to understand this feature more. Can we sync (you me and @landaverde1196) about it this week?
