### ISSUE TITLE
Android Build and Beta APK

### ISSUE THREAD

**Issue by detroitpro** [akroma-project/akroma-wallet-mobile#46]
**Describe the problem**
When new features are merged into main, there is no CI/CD process that creates an APK. Since there is no APK there is not an automated way for external testers to get access to new builds.

**Describe the solution you'd like**
Configure Bitrise to create APKs when new features are merged into main. I believe that Bitrise can do this without access to the PlayStore.

If access to the PlayStore is required, we can configure Bitrise to push to the store - actually, I'd like us to learn about using Bitrise to do this - once we have builds passing, APKs being created, I'd like us to push them to the Play store. 

**Additional context**
I can grant access to anyone that needs.

**Comment by karlakrrasco** [comment]
@Argude01 the APK was already implemented for the Akroma project correct?

**Comment by Argude01** [comment]
@Luigy08 @cafadev BLOCKER: Waiting for the PR to testing in Bitrise the deploy workflow
