### ISSUE TITLE
Acquire AKA

### ISSUE THREAD

**Issue by karlakrrasco** [akroma-project/akroma-wallet-mobile#65]
**Description**
Create a document explaining the process of acquiring AKA (Buying them & Receiving via transfer)

- Where to buy them?
- How much do they cost?
- How to build on Akroma?

**Documentation must be added here:** 
https://docs.akroma.org/

**Comment by detroitpro** [comment]
@karlakrrasco - we can add documentation to the official documentation site. https://docs.akroma.org/

However; I'd rather we focus on teaching people how to build on Akroma.
