### ISSUE TITLE
Add decimal numbers format

### ISSUE THREAD

**Issue by karlakrrasco** [akroma-project/akroma-wallet-mobile#70]
Currently, the AKA balance is only listed as 1234.908 it should be correctly separated on decimals

**Comment by detroitpro** [comment]
Isn't 1234.908 in the correct format? 

What are you expecting?

**Comment by detroitpro** [comment]
@karlakrrasco - what format ?

**Comment by karlakrrasco** [comment]
the format expected is 1,234.08
