### ISSUE TITLE
Select where to save the keystore Local Disk or iCloud

### ISSUE THREAD

**Issue by cafadev** [akroma-project/akroma-wallet-mobile#73]
**Describe the problem**
Give the user options where to save the keystore, local disk or iCloud.

**Describe the solution you'd like**
The file should be named with the format [wallet-name].[address].json
NOTE: wallet-name should be sanitized = remove all special chars and spaces

**Comment by adonayvasquezz** [comment]
@detroitpro I need access to a development team account to continue with this card, that is required to be able to add Icloud capability in Xcode
